<?php
/**
* Valid permissions for this module
* @return array An array of valid permissions for the onthisdate module
*/
function fblike_perm() {
	return array('access onthisdate content');
}

function fblike_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
	$options = array(
		'fragment' => '',
		'query' => '',
		'absolute' => TRUE,
		'alias' => FALSE,
		'prefix' => ''
	);
	$node_path = "node/" . $node->nid;
	$node_url = urlencode(url($node_path, $options));
	switch ($op) {
		case 'submit':
		case 'insert':
		case 'update':
		case 'view':
			$like_template = "<iframe src='http://www.facebook.com/plugins/like.php?href=$node_url&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light' scrolling='no' frameborder='0' allowTransparency='true' style='border:none; overflow:hidden; width:450px; height:px'></iframe>";
			$the_orig_body = $node->content['body']['#value'];
			$node->content['body']['#value'] = "$like_template" . $the_orig_body;
		break;
	}
}

